WITH T AS(SELECT AUTHOR_ID, CATEGORY, SUM(PRICE*S) AS TOTAL_SALES
FROM BOOK AS B JOIN (SELECT BOOK_ID, SUM(SALES) AS S
FROM BOOK_SALES 
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY BOOK_ID) AS TEM ON B.BOOK_ID = TEM.BOOK_ID
GROUP BY AUTHOR_ID, CATEGORY)

SELECT T.AUTHOR_ID, AUTHOR.AUTHOR_NAME, T.CATEGORY, T.TOTAL_SALES
FROM T JOIN AUTHOR ON T.AUTHOR_ID = AUTHOR.AUTHOR_ID
ORDER BY T.AUTHOR_ID,T.CATEGORY DESC