WITH RECURSIVE GENERATIONS AS 
(SELECT ID, PARENT_ID, 1 AS GENERATION
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL

UNION ALL
SELECT A.ID, A.PARENT_ID, B.GENERATION + 1 AS GENERATION
FROM ECOLI_DATA AS A JOIN GENERATIONS AS B ON A.PARENT_ID = B.ID)

SELECT A.ID
FROM GENERATIONS AS A
WHERE A.GENERATION = 3 
ORDER BY A.ID