SELECT PRODUCT_CODE, (C*PRICE) AS SALES
FROM PRODUCT,
    (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS C
    FROM OFFLINE_SALE 
    GROUP BY PRODUCT_ID) AS TEM
WHERE PRODUCT.PRODUCT_ID = TEM.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE