SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE*30*(100-C.DISCOUNT_RATE)/100,0)  AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON A.CAR_TYPE = C.CAR_TYPE
WHERE C.DURATION_TYPE LIKE '30일%' AND A.CAR_TYPE IN ('SUV', '세단') AND A.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE<'2022-12-01' AND END_DATE>'2022-11-01')
GROUP BY A.CAR_ID
HAVING FEE >=500000 AND FEE<2000000
ORDER BY FEE DESC,A.CAR_TYPE, A.CAR_ID DESC