SELECT T.ID,
CASE WHEN T.PER >=0.75 THEN 'CRITICAL'
WHEN T.PER >=0.5 THEN 'HIGH'
WHEN T.PER >=0.25 THEN 'MEDIUM'
ELSE 'LOW' END AS COLONY_NAME
FROM 
(SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS PER
FROM ECOLI_DATA) AS T
ORDER BY T.ID