SELECT AA.ID,
CASE WHEN AA.PER>=0.75 THEN 'CRITICAL'
WHEN AA.PER>=0.50 THEN 'HIGH'
WHEN AA.PER>=0.25 THEN 'MEDIUM'
ELSE 'LOW' END AS COLONY_NAME
FROM (SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS PER
FROM ECOLI_DATA) AS AA 
ORDER BY AA.ID