WITH RECURSIVE GENERATIONS AS 
(SELECT ID, PARENT_ID, 1 AS GENERATION
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL

UNION ALL
SELECT A.ID, A.PARENT_ID, B.GENERATION + 1 AS GENERATION
FROM ECOLI_DATA AS A JOIN GENERATIONS AS B ON A.PARENT_ID = B.ID)

SELECT COUNT(*) AS COUNT, A.GENERATION
FROM GENERATIONS AS A LEFT JOIN GENERATIONS AS B ON A.ID = B.PARENT_ID
WHERE B.PARENT_ID IS NULL
GROUP BY A.GENERATION
ORDER BY A.GENERATION