WITH RECURSIVE GENERATIONS AS (
    # 재귀 쿼리
    # 초기화
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    SELECT A.ID, A.PARENT_ID, G.GENERATION+1
    FROM ECOLI_DATA AS A JOIN GENERATIONS AS G
    ON G.ID = A.PARENT_ID
)

SELECT COUNT(*) AS COUNT, A.GENERATION
FROM GENERATIONS AS A
WHERE NOT EXISTS 
(SELECT 1
FROM ECOLI_DATA AS B
WHERE A.ID = B.PARENT_ID)
GROUP BY A.GENERATION