SELECT TEM.HISTORY_ID, 
CASE 
WHEN TEM.DURATION >= 90 THEN ROUND(TEM.DAILY_FEE * (100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '90일%'))*0.01*TEM.DURATION)
WHEN TEM.DURATION >= 30 THEN ROUND(TEM.DAILY_FEE * (100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '30일%'))*0.01*TEM.DURATION)
WHEN TEM.DURATION >= 7 THEN ROUND(TEM.DAILY_FEE * (100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '7일%'))*0.01*TEM.DURATION) 
ELSE ROUND(TEM.DAILY_FEE * TEM.DURATION)  END AS FEE
FROM 
(SELECT A.DAILY_FEE, B.HISTORY_ID, A.CAR_ID, DATEDIFF(END_DATE,START_DATE) + 1 AS DURATION FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID WHERE A.CAR_TYPE = '트럭') AS TEM
ORDER BY FEE DESC, TEM.HISTORY_ID DESC