-- 코드를 입력하세요
SELECT USED_GOODS_USER.USER_ID, USED_GOODS_USER.NICKNAME,TEM.PRICE AS TOTAL_SALES
FROM USED_GOODS_USER JOIN (
SELECT WRITER_ID, SUM(PRICE) AS PRICE
FROM USED_GOODS_BOARD 
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID HAVING SUM(PRICE)>=700000) AS TEM
ON USED_GOODS_USER.USER_ID = TEM.WRITER_ID
ORDER BY TOTAL_SALES