SELECT EMP_NO, EMP_NAME, 
CASE WHEN SCORE >=96 THEN 'S'
WHEN SCORE >= 90 THEN 'A'
WHEN SCORE >= 80 THEN 'B'
ELSE 'C' END AS GRADE,
CASE WHEN SCORE >=96 THEN SAL*0.2
WHEN SCORE >= 90 THEN SAL*0.15
WHEN SCORE >= 80 THEN SAL*0.1
ELSE 0 END AS BONUS
FROM 
(SELECT A.EMP_NO, A.EMP_NAME, AVG(B.SCORE) AS SCORE, A.SAL
FROM HR_EMPLOYEES AS A JOIN HR_GRADE AS B ON A.EMP_NO = B.EMP_NO
GROUP BY A.EMP_NO) AS TEM
ORDER BY EMP_NO