WITH TEM AS (SELECT EMP_NO, AVG(SCORE) AS SCORE
FROM HR_GRADE
GROUP BY EMP_NO)

SELECT HR_EMPLOYEES.EMP_NO AS EMP_NO, EMP_NAME, 
CASE WHEN TEM.SCORE>=96 THEN 'S'
WHEN TEM.SCORE>=90 THEN 'A'
WHEN TEM.SCORE>=80 THEN 'B'
ELSE 'C' END AS GRADE,
CASE WHEN TEM.SCORE>=96 THEN ROUND(SAL*0.02,0)
WHEN TEM.SCORE>=90 THEN ROUND(SAL*0.15)
WHEN TEM.SCORE>=80 THEN ROUND(SAL*0.10)
ELSE 0 END AS BONUS
FROM HR_EMPLOYEES JOIN TEM ON HR_EMPLOYEES.EMP_NO = TEM.EMP_NO
ORDER BY EMP_NO