WITH AA AS (SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID 
ORDER BY COUNT(MEMBER_ID) DESC
LIMIT 1)

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS P JOIN REST_REVIEW AS R ON P.MEMBER_ID = R.MEMBER_ID
WHERE P.MEMBER_ID = (SELECT MEMBER_ID FROM AA)
ORDER BY REVIEW_DATE, R.REVIEW_TEXT