-- 코드를 입력하세요
SELECT DISTINCT FIRST_HALF.FLAVOR 
FROM FIRST_HALF, ICECREAM_INFO 
WHERE FIRST_HALF.TOTAL_ORDER>3000 and ICECREAM_INFO.INGREDIENT_TYPE='fruit_based'and FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
ORDER BY FIRST_HALF.TOTAL_ORDER DESC;