SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
WHERE (B.FISH_NAME, A.LENGTH) IN 
(SELECT FISH_NAME, MAX(LENGTH)
FROM FISH_INFO AS A JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY FISH_NAME)
ORDER BY A.ID