-- 코드를 작성해주세요
SELECT TEM.SCORE AS SCORE, HR_EMPLOYEES.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES,  (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE 
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1

) AS TEM
WHERE HR_EMPLOYEES.EMP_NO = TEM.EMP_NO
