-- 코드를 입력하세요
SELECT CATEGORY, SUM(S) AS TOTAL_SALES
FROM BOOK JOIN (SELECT BOOK_ID, SUM(SALES) AS S
FROM BOOK_SALES 
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY BOOK_ID) AS TEM ON BOOK.BOOK_ID = TEM.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY