-- 코드를 입력하세요
# SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
# FROM FOOD_PRODUCT AS F JOIN 
# (SELECT PRODUCT_ID, CATEGORY, MAX(PRICE)
# FROM FOOD_PRODUCT WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
# GROUP BY CATEGORY) 
# AS TEM ON F.PRODUCT_ID = TEM.PRODUCT_ID
# ORDER BY MAX_PRICE DESC
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F JOIN (SELECT CATEGORY, MAX(PRICE) AS M
FROM FOOD_PRODUCT WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY) AS TEM ON F.CATEGORY = TEM.CATEGORY AND F.PRICE = TEM.M
ORDER BY MAX_PRICE DESC